/**
 *
 * E-learning Module for Magnolia CMS (http://www.openmindlab.com/lab/products/lms.html)
 * Copyright(C) 2010-2013, Openmind S.r.l. http://www.openmindonline.it
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 12:53:38 PM CEST 
//

package net.sourceforge.openutils.mgnllms.scorm.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

import net.sourceforge.openutils.mgnllms.scorm.model.imsss.SequencingCollection;


/**
 * <p>
 * Java class for manifest complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="manifest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imscp_v1p1}metadata" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imscp_v1p1}organizations"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imscp_v1p1}resources"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imscp_v1p1}manifest" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsss}sequencingCollection" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imscp_v1p1}attr.version"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imscp_v1p1}attr.identifier.req"/>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}base"/>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "manifest", propOrder = {"metadata", "organizations", "resources", "manifest", "sequencingCollection" })
public class Manifest
{

    protected Metadata metadata;

    @XmlElement(required = true)
    protected Organizations organizations;

    @XmlElement(required = true)
    protected Resources resources;

    protected List<Manifest> manifest;

    @XmlElement(namespace = "http://www.imsglobal.org/xsd/imsss")
    protected SequencingCollection sequencingCollection;

    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;

    @XmlAttribute
    protected String version;

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String identifier;

    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the metadata property.
     * @return possible object is {@link Metadata }
     */
    public Metadata getMetadata()
    {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * @param value allowed object is {@link Metadata }
     */
    public void setMetadata(Metadata value)
    {
        this.metadata = value;
    }

    /**
     * Gets the value of the organizations property.
     * @return possible object is {@link Organizations }
     */
    public Organizations getOrganizations()
    {
        return organizations;
    }

    /**
     * Sets the value of the organizations property.
     * @param value allowed object is {@link Organizations }
     */
    public void setOrganizations(Organizations value)
    {
        this.organizations = value;
    }

    /**
     * Gets the value of the resources property.
     * @return possible object is {@link Resources }
     */
    public Resources getResources()
    {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     * @param value allowed object is {@link Resources }
     */
    public void setResources(Resources value)
    {
        this.resources = value;
    }

    /**
     * Gets the value of the manifest property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the manifest property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     *    getManifest().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Manifest }
     */
    public List<Manifest> getManifest()
    {
        if (manifest == null)
        {
            manifest = new ArrayList<Manifest>();
        }
        return this.manifest;
    }

    /**
     * Gets the value of the sequencingCollection property.
     * @return possible object is {@link SequencingCollection }
     */
    public SequencingCollection getSequencingCollection()
    {
        return sequencingCollection;
    }

    /**
     * Sets the value of the sequencingCollection property.
     * @param value allowed object is {@link SequencingCollection }
     */
    public void setSequencingCollection(SequencingCollection value)
    {
        this.sequencingCollection = value;
    }

    /**
     * Gets the value of the base property.
     * @return possible object is {@link String }
     */
    public String getBase()
    {
        return base;
    }

    /**
     * Sets the value of the base property.
     * @param value allowed object is {@link String }
     */
    public void setBase(String value)
    {
        this.base = value;
    }

    /**
     * Gets the value of the version property.
     * @return possible object is {@link String }
     */
    public String getVersion()
    {
        return version;
    }

    /**
     * Sets the value of the version property.
     * @param value allowed object is {@link String }
     */
    public void setVersion(String value)
    {
        this.version = value;
    }

    /**
     * Gets the value of the identifier property.
     * @return possible object is {@link String }
     */
    public String getIdentifier()
    {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * @param value allowed object is {@link String }
     */
    public void setIdentifier(String value)
    {
        this.identifier = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * <p>
     * the map is keyed by the name of the attribute and the value is the string value of the attribute. the map
     * returned by this method is live, and you can add new attribute by updating the map directly. Because of this
     * design, there's no setter.
     * @return always non-null
     */
    public Map<QName, String> getOtherAttributes()
    {
        return otherAttributes;
    }

}
