/**
 *
 * E-learning Module for Magnolia CMS (http://www.openmindlab.com/lab/products/lms.html)
 * Copyright(C) 2010-2013, Openmind S.r.l. http://www.openmindonline.it
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 12:53:38 PM CEST 
//

package net.sourceforge.openutils.mgnllms.scorm.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>
 * Java class for metadata complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="metadata">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imscp_v1p1}schema" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imscp_v1p1}schemaversion" minOccurs="0"/>
 *         &lt;element ref="{http://www.adlnet.org/xsd/adlcp_v1p3}location" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "metadata", propOrder = {"schema", "schemaversion", "location" })
public class Metadata
{

    protected String schema;

    protected String schemaversion;

    @XmlElement(namespace = "http://www.adlnet.org/xsd/adlcp_v1p3")
    protected List<String> location;

    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the schema property.
     * @return possible object is {@link String }
     */
    public String getSchema()
    {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     * @param value allowed object is {@link String }
     */
    public void setSchema(String value)
    {
        this.schema = value;
    }

    /**
     * Gets the value of the schemaversion property.
     * @return possible object is {@link String }
     */
    public String getSchemaversion()
    {
        return schemaversion;
    }

    /**
     * Sets the value of the schemaversion property.
     * @param value allowed object is {@link String }
     */
    public void setSchemaversion(String value)
    {
        this.schemaversion = value;
    }

    /**
     * Gets the value of the location property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the location property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     *    getLocation().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     */
    public List<String> getLocation()
    {
        if (location == null)
        {
            location = new ArrayList<String>();
        }
        return this.location;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * <p>
     * the map is keyed by the name of the attribute and the value is the string value of the attribute. the map
     * returned by this method is live, and you can add new attribute by updating the map directly. Because of this
     * design, there's no setter.
     * @return always non-null
     */
    public Map<QName, String> getOtherAttributes()
    {
        return otherAttributes;
    }

}
