/**
 *
 * E-learning Module for Magnolia CMS (http://www.openmindlab.com/lab/products/lms.html)
 * Copyright(C) 2010-2011, Openmind S.r.l. http://www.openmindonline.it
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 12:53:38 PM CEST 
//

package net.sourceforge.openutils.mgnllms.scorm.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * net.sourceforge.openutils.mgnllms.scorm.model package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 */
@XmlRegistry
public class ObjectFactory
{

    private final static QName _File_QNAME = new QName("http://www.imsglobal.org/xsd/imscp_v1p1", "file");

    private final static QName _Organization_QNAME = new QName(
        "http://www.imsglobal.org/xsd/imscp_v1p1",
        "organization");

    private final static QName _Title_QNAME = new QName("http://www.imsglobal.org/xsd/imscp_v1p1", "title");

    private final static QName _Dependency_QNAME = new QName("http://www.imsglobal.org/xsd/imscp_v1p1", "dependency");

    private final static QName _Schema_QNAME = new QName("http://www.imsglobal.org/xsd/imscp_v1p1", "schema");

    private final static QName _Metadata_QNAME = new QName("http://www.imsglobal.org/xsd/imscp_v1p1", "metadata");

    private final static QName _Schemaversion_QNAME = new QName(
        "http://www.imsglobal.org/xsd/imscp_v1p1",
        "schemaversion");

    private final static QName _Resources_QNAME = new QName("http://www.imsglobal.org/xsd/imscp_v1p1", "resources");

    private final static QName _Manifest_QNAME = new QName("http://www.imsglobal.org/xsd/imscp_v1p1", "manifest");

    private final static QName _Item_QNAME = new QName("http://www.imsglobal.org/xsd/imscp_v1p1", "item");

    private final static QName _Organizations_QNAME = new QName(
        "http://www.imsglobal.org/xsd/imscp_v1p1",
        "organizations");

    private final static QName _Resource_QNAME = new QName("http://www.imsglobal.org/xsd/imscp_v1p1", "resource");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * net.sourceforge.openutils.mgnllms.scorm.model
     */
    public ObjectFactory()
    {
    }

    /**
     * Create an instance of {@link Organization }
     */
    public Organization createOrganization()
    {
        return new Organization();
    }

    /**
     * Create an instance of {@link Organizations }
     */
    public Organizations createOrganizations()
    {
        return new Organizations();
    }

    /**
     * Create an instance of {@link Resources }
     */
    public Resources createResources()
    {
        return new Resources();
    }

    /**
     * Create an instance of {@link Item }
     */
    public Item createItem()
    {
        return new Item();
    }

    /**
     * Create an instance of {@link Resource }
     */
    public Resource createResource()
    {
        return new Resource();
    }

    /**
     * Create an instance of {@link Metadata }
     */
    public Metadata createMetadata()
    {
        return new Metadata();
    }

    /**
     * Create an instance of {@link File }
     */
    public File createFile()
    {
        return new File();
    }

    /**
     * Create an instance of {@link Dependency }
     */
    public Dependency createDependency()
    {
        return new Dependency();
    }

    /**
     * Create an instance of {@link Manifest }
     */
    public Manifest createManifest()
    {
        return new Manifest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link File }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imscp_v1p1", name = "file")
    public JAXBElement<File> createFile(File value)
    {
        return new JAXBElement<File>(_File_QNAME, File.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Organization }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imscp_v1p1", name = "organization")
    public JAXBElement<Organization> createOrganization(Organization value)
    {
        return new JAXBElement<Organization>(_Organization_QNAME, Organization.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imscp_v1p1", name = "title")
    public JAXBElement<String> createTitle(String value)
    {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Dependency }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imscp_v1p1", name = "dependency")
    public JAXBElement<Dependency> createDependency(Dependency value)
    {
        return new JAXBElement<Dependency>(_Dependency_QNAME, Dependency.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imscp_v1p1", name = "schema")
    public JAXBElement<String> createSchema(String value)
    {
        return new JAXBElement<String>(_Schema_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Metadata }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imscp_v1p1", name = "metadata")
    public JAXBElement<Metadata> createMetadata(Metadata value)
    {
        return new JAXBElement<Metadata>(_Metadata_QNAME, Metadata.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imscp_v1p1", name = "schemaversion")
    public JAXBElement<String> createSchemaversion(String value)
    {
        return new JAXBElement<String>(_Schemaversion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resources }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imscp_v1p1", name = "resources")
    public JAXBElement<Resources> createResources(Resources value)
    {
        return new JAXBElement<Resources>(_Resources_QNAME, Resources.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Manifest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imscp_v1p1", name = "manifest")
    public JAXBElement<Manifest> createManifest(Manifest value)
    {
        return new JAXBElement<Manifest>(_Manifest_QNAME, Manifest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Item }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imscp_v1p1", name = "item")
    public JAXBElement<Item> createItem(Item value)
    {
        return new JAXBElement<Item>(_Item_QNAME, Item.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Organizations }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imscp_v1p1", name = "organizations")
    public JAXBElement<Organizations> createOrganizations(Organizations value)
    {
        return new JAXBElement<Organizations>(_Organizations_QNAME, Organizations.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resource }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imscp_v1p1", name = "resource")
    public JAXBElement<Resource> createResource(Resource value)
    {
        return new JAXBElement<Resource>(_Resource_QNAME, Resource.class, null, value);
    }

}
