/**
 *
 * E-learning Module for Magnolia CMS (http://www.openmindlab.com/lab/products/lms.html)
 * Copyright(C) 2010-2011, Openmind S.r.l. http://www.openmindonline.it
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 12:53:38 PM CEST 
//

package net.sourceforge.openutils.mgnllms.scorm.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

import net.sourceforge.openutils.mgnllms.scorm.model.cp.CompletionThreshold;
import net.sourceforge.openutils.mgnllms.scorm.model.cp.Data;
import net.sourceforge.openutils.mgnllms.scorm.model.cp.TimeLimitAction;
import net.sourceforge.openutils.mgnllms.scorm.model.imsss.Sequencing;


/**
 * <p>
 * Java class for organization complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="organization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imscp_v1p1}title" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imscp_v1p1}item" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imscp_v1p1}metadata" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsss}sequencing" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imscp_v1p1}attr.identifier.req"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imscp_v1p1}attr.structure.req"/>
 *       &lt;attribute ref="{http://www.adlnet.org/xsd/adlseq_v1p3}objectivesGlobalToSystem"/>
 *       &lt;attribute ref="{http://www.adlnet.org/xsd/adlcp_v1p3}sharedDataGlobalToSystem"/>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "organization", propOrder = {"title", "item", "metadata", "sequencing", "completionThreshold" })
public class Organization implements CommonDataItemOrganization
{

    protected String title;

    @XmlElement(required = true)
    protected List<Item> item;

    protected Metadata metadata;

    @XmlElement(namespace = "http://www.imsglobal.org/xsd/imsss")
    protected Sequencing sequencing;

    @XmlAttribute(namespace = "http://www.adlnet.org/xsd/adlseq_v1p3")
    protected Boolean objectivesGlobalToSystem;

    @XmlAttribute(namespace = "http://www.adlnet.org/xsd/adlcp_v1p3")
    protected Boolean sharedDataGlobalToSystem;

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String identifier;

    @XmlAttribute
    protected String structure;

    @XmlElement(namespace = "http://www.adlnet.org/xsd/adlcp_v1p3")
    protected CompletionThreshold completionThreshold;

    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the title property.
     * @return possible object is {@link String }
     */
    public String getTitle()
    {
        return title;
    }

    /**
     * Sets the value of the title property.
     * @param value allowed object is {@link String }
     */
    public void setTitle(String value)
    {
        this.title = value;
    }

    /**
     * Gets the value of the item property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the item property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Item }
     */
    public List<Item> getItem()
    {
        if (item == null)
        {
            item = new ArrayList<Item>();
        }
        return this.item;
    }

    /**
     * Gets the value of the metadata property.
     * @return possible object is {@link Metadata }
     */
    public Metadata getMetadata()
    {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * @param value allowed object is {@link Metadata }
     */
    public void setMetadata(Metadata value)
    {
        this.metadata = value;
    }

    /**
     * Gets the value of the sequencing property.
     * @return possible object is {@link Sequencing }
     */
    public Sequencing getSequencing()
    {
        return sequencing;
    }

    /**
     * Sets the value of the sequencing property.
     * @param value allowed object is {@link Sequencing }
     */
    public void setSequencing(Sequencing value)
    {
        this.sequencing = value;
    }

    /**
     * Gets the value of the objectivesGlobalToSystem property.
     * @return possible object is {@link Boolean }
     */
    public boolean isObjectivesGlobalToSystem()
    {
        if (objectivesGlobalToSystem == null)
        {
            return true;
        }
        else
        {
            return objectivesGlobalToSystem;
        }
    }

    /**
     * Sets the value of the objectivesGlobalToSystem property.
     * @param value allowed object is {@link Boolean }
     */
    public void setObjectivesGlobalToSystem(Boolean value)
    {
        this.objectivesGlobalToSystem = value;
    }

    /**
     * Gets the value of the sharedDataGlobalToSystem property.
     * @return possible object is {@link Boolean }
     */
    public boolean isSharedDataGlobalToSystem()
    {
        if (sharedDataGlobalToSystem == null)
        {
            return true;
        }
        else
        {
            return sharedDataGlobalToSystem;
        }
    }

    /**
     * Sets the value of the sharedDataGlobalToSystem property.
     * @param value allowed object is {@link Boolean }
     */
    public void setSharedDataGlobalToSystem(Boolean value)
    {
        this.sharedDataGlobalToSystem = value;
    }

    /**
     * Gets the value of the identifier property.
     * @return possible object is {@link String }
     */
    public String getIdentifier()
    {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * @param value allowed object is {@link String }
     */
    public void setIdentifier(String value)
    {
        this.identifier = value;
    }

    /**
     * Gets the value of the structure property.
     * @return possible object is {@link String }
     */
    public String getStructure()
    {
        if (structure == null)
        {
            return "hierarchical";
        }
        else
        {
            return structure;
        }
    }

    /**
     * Sets the value of the structure property.
     * @param value allowed object is {@link String }
     */
    public void setStructure(String value)
    {
        this.structure = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * <p>
     * the map is keyed by the name of the attribute and the value is the string value of the attribute. the map
     * returned by this method is live, and you can add new attribute by updating the map directly. Because of this
     * design, there's no setter.
     * @return always non-null
     */
    public Map<QName, String> getOtherAttributes()
    {
        return otherAttributes;
    }

    /**
     * Returns the completionThreshold.
     * @return the completionThreshold
     */
    public CompletionThreshold getCompletionThreshold()
    {
        return completionThreshold;
    }

    /**
     * Sets the completionThreshold.
     * @param completionThreshold the completionThreshold to set
     */
    public void setCompletionThreshold(CompletionThreshold completionThreshold)
    {
        this.completionThreshold = completionThreshold;
    }

    /**
     * {@inheritDoc}
     */
    public String getDataFromLMS()
    {
        /*
         * Inserito per poter estendere l'interfaccia commonDataItemOrganization, in realtà non può essere presente
         * all'interno di un'organization
         */
        return null;
    }

    /**
     * {@inheritDoc}
     */
    public TimeLimitAction getTimeLimitAction()
    {
        // come sopra
        return null;
    }

    /**
     * {@inheritDoc}
     */
    public Data getData()
    {
        // come sopra
        return null;
    }

}
