/**
 *
 * E-learning Module for Magnolia CMS (http://www.openmindlab.com/lab/products/lms.html)
 * Copyright(C) 2010-2012, Openmind S.r.l. http://www.openmindonline.it
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 12:53:38 PM CEST 
//

package net.sourceforge.openutils.mgnllms.scorm.model.cp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * net.sourceforge.openutils.mgnllms.scorm.model.cp package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 */
@XmlRegistry
public class ObjectFactory
{

    private final static QName _Map_QNAME = new QName("http://www.adlnet.org/xsd/adlcp_v1p3", "map");

    private final static QName _DataFromLMS_QNAME = new QName("http://www.adlnet.org/xsd/adlcp_v1p3", "dataFromLMS");

    private final static QName _Data_QNAME = new QName("http://www.adlnet.org/xsd/adlcp_v1p3", "data");

    private final static QName _Location_QNAME = new QName("http://www.adlnet.org/xsd/adlcp_v1p3", "location");

    private final static QName _TimeLimitAction_QNAME = new QName(
        "http://www.adlnet.org/xsd/adlcp_v1p3",
        "timeLimitAction");

    private final static QName _CompletionThreshold_QNAME = new QName(
        "http://www.adlnet.org/xsd/adlcp_v1p3",
        "completionThreshold");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * net.sourceforge.openutils.mgnllms.scorm.model.cp
     */
    public ObjectFactory()
    {
    }

    /**
     * Create an instance of {@link CompletionThreshold }
     */
    public CompletionThreshold createCompletionThreshold()
    {
        return new CompletionThreshold();
    }

    /**
     * Create an instance of {@link Data }
     */
    public Data createData()
    {
        return new Data();
    }

    /**
     * Create an instance of {@link Map }
     */
    public Map createMap()
    {
        return new Map();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Map }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlcp_v1p3", name = "map")
    public JAXBElement<Map> createMap(Map value)
    {
        return new JAXBElement<Map>(_Map_QNAME, Map.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlcp_v1p3", name = "dataFromLMS")
    public JAXBElement<String> createDataFromLMS(String value)
    {
        return new JAXBElement<String>(_DataFromLMS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Data }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlcp_v1p3", name = "data")
    public JAXBElement<Data> createData(Data value)
    {
        return new JAXBElement<Data>(_Data_QNAME, Data.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlcp_v1p3", name = "location")
    public JAXBElement<String> createLocation(String value)
    {
        return new JAXBElement<String>(_Location_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeLimitAction }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlcp_v1p3", name = "timeLimitAction")
    public JAXBElement<TimeLimitAction> createTimeLimitAction(TimeLimitAction value)
    {
        return new JAXBElement<TimeLimitAction>(_TimeLimitAction_QNAME, TimeLimitAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompletionThreshold }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlcp_v1p3", name = "completionThreshold")
    public JAXBElement<CompletionThreshold> createCompletionThreshold(CompletionThreshold value)
    {
        return new JAXBElement<CompletionThreshold>(_CompletionThreshold_QNAME, CompletionThreshold.class, null, value);
    }

}
