/**
 *
 * E-learning Module for Magnolia CMS (http://www.openmindlab.com/lab/products/lms.html)
 * Copyright(C) 2010-2013, Openmind S.r.l. http://www.openmindonline.it
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 12:53:38 PM CEST 
//

package net.sourceforge.openutils.mgnllms.scorm.model.seq;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for constrainChoiceConsiderations complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="constrainChoiceConsiderations">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="preventActivation" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="constrainChoice" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "constrainChoiceConsiderations")
public class ConstrainChoiceConsiderations
{

    @XmlAttribute
    protected Boolean preventActivation;

    @XmlAttribute
    protected Boolean constrainChoice;

    /**
     * Gets the value of the preventActivation property.
     * @return possible object is {@link Boolean }
     */
    public boolean isPreventActivation()
    {
        if (preventActivation == null)
        {
            return false;
        }
        else
        {
            return preventActivation;
        }
    }

    /**
     * Sets the value of the preventActivation property.
     * @param value allowed object is {@link Boolean }
     */
    public void setPreventActivation(Boolean value)
    {
        this.preventActivation = value;
    }

    /**
     * Gets the value of the constrainChoice property.
     * @return possible object is {@link Boolean }
     */
    public boolean isConstrainChoice()
    {
        if (constrainChoice == null)
        {
            return false;
        }
        else
        {
            return constrainChoice;
        }
    }

    /**
     * Sets the value of the constrainChoice property.
     * @param value allowed object is {@link Boolean }
     */
    public void setConstrainChoice(Boolean value)
    {
        this.constrainChoice = value;
    }

}
