/**
 *
 * E-learning Module for Magnolia CMS (http://www.openmindlab.com/lab/products/lms.html)
 * Copyright(C) 2010-2013, Openmind S.r.l. http://www.openmindonline.it
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 12:53:38 PM CEST 
//

package net.sourceforge.openutils.mgnllms.scorm.model.seq;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * net.sourceforge.openutils.mgnllms.scorm.model.seq package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 */
@XmlRegistry
public class ObjectFactory
{

    private final static QName _Objectives_QNAME = new QName("http://www.adlnet.org/xsd/adlseq_v1p3", "objectives");

    private final static QName _MapInfo_QNAME = new QName("http://www.adlnet.org/xsd/adlseq_v1p3", "mapInfo");

    private final static QName _Objective_QNAME = new QName("http://www.adlnet.org/xsd/adlseq_v1p3", "objective");

    private final static QName _RollupConsiderations_QNAME = new QName(
        "http://www.adlnet.org/xsd/adlseq_v1p3",
        "rollupConsiderations");

    private final static QName _ConstrainedChoiceConsiderations_QNAME = new QName(
        "http://www.adlnet.org/xsd/adlseq_v1p3",
        "constrainedChoiceConsiderations");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * net.sourceforge.openutils.mgnllms.scorm.model.seq
     */
    public ObjectFactory()
    {
    }

    /**
     * Create an instance of {@link RollupConsiderations }
     */
    public RollupConsiderations createRollupConsiderations()
    {
        return new RollupConsiderations();
    }

    /**
     * Create an instance of {@link Objective }
     */
    public Objective createObjective()
    {
        return new Objective();
    }

    /**
     * Create an instance of {@link Objectives }
     */
    public Objectives createObjectives()
    {
        return new Objectives();
    }

    /**
     * Create an instance of {@link ConstrainChoiceConsiderations }
     */
    public ConstrainChoiceConsiderations createConstrainChoiceConsiderations()
    {
        return new ConstrainChoiceConsiderations();
    }

    /**
     * Create an instance of {@link MapInfo }
     */
    public MapInfo createMapInfo()
    {
        return new MapInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Objectives }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlseq_v1p3", name = "objectives")
    public JAXBElement<Objectives> createObjectives(Objectives value)
    {
        return new JAXBElement<Objectives>(_Objectives_QNAME, Objectives.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MapInfo }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlseq_v1p3", name = "mapInfo")
    public JAXBElement<MapInfo> createMapInfo(MapInfo value)
    {
        return new JAXBElement<MapInfo>(_MapInfo_QNAME, MapInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Objective }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlseq_v1p3", name = "objective")
    public JAXBElement<Objective> createObjective(Objective value)
    {
        return new JAXBElement<Objective>(_Objective_QNAME, Objective.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RollupConsiderations }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlseq_v1p3", name = "rollupConsiderations")
    public JAXBElement<RollupConsiderations> createRollupConsiderations(RollupConsiderations value)
    {
        return new JAXBElement<RollupConsiderations>(
            _RollupConsiderations_QNAME,
            RollupConsiderations.class,
            null,
            value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConstrainChoiceConsiderations }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlseq_v1p3", name = "constrainedChoiceConsiderations")
    public JAXBElement<ConstrainChoiceConsiderations> createConstrainedChoiceConsiderations(
        ConstrainChoiceConsiderations value)
    {
        return new JAXBElement<ConstrainChoiceConsiderations>(
            _ConstrainedChoiceConsiderations_QNAME,
            ConstrainChoiceConsiderations.class,
            null,
            value);
    }

}
