/**
 *
 * E-learning Module for Magnolia CMS (http://www.openmindlab.com/lab/products/lms.html)
 * Copyright(C) 2010-2012, Openmind S.r.l. http://www.openmindonline.it
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 12:53:38 PM CEST 
//

package net.sourceforge.openutils.mgnllms.scorm.model.seq;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for objective complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="objective">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.adlnet.org/xsd/adlseq_v1p3}mapInfo" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="objectiveID" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "objective", propOrder = {"mapInfo" })
public class Objective
{

    @XmlElement(required = true)
    protected List<MapInfo> mapInfo;

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String objectiveID;

    /**
     * Gets the value of the mapInfo property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the mapInfo property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     *    getMapInfo().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link MapInfo }
     */
    public List<MapInfo> getMapInfo()
    {
        if (mapInfo == null)
        {
            mapInfo = new ArrayList<MapInfo>();
        }
        return this.mapInfo;
    }

    /**
     * Gets the value of the objectiveID property.
     * @return possible object is {@link String }
     */
    public String getObjectiveID()
    {
        return objectiveID;
    }

    /**
     * Sets the value of the objectiveID property.
     * @param value allowed object is {@link String }
     */
    public void setObjectiveID(String value)
    {
        this.objectiveID = value;
    }

}
