/**
 *
 * E-learning Module for Magnolia CMS (http://www.openmindlab.com/lab/products/lms.html)
 * Copyright(C) 2010-2012, Openmind S.r.l. http://www.openmindonline.it
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 12:53:38 PM CEST 
//

package net.sourceforge.openutils.mgnllms.scorm.model.imsss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * The type associated with a control-mode element (see the element controlMode)
 * <p>
 * Java class for controlMode complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="controlMode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="choice" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="choiceExit" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="flow" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="forwardOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="useCurrentAttemptObjectiveInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="useCurrentAttemptProgressInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "controlMode")
public class ControlMode
{

    @XmlAttribute
    protected Boolean choice;

    @XmlAttribute
    protected Boolean choiceExit;

    @XmlAttribute
    protected Boolean flow;

    @XmlAttribute
    protected Boolean forwardOnly;

    @XmlAttribute
    protected Boolean useCurrentAttemptObjectiveInfo;

    @XmlAttribute
    protected Boolean useCurrentAttemptProgressInfo;

    /**
     * Gets the value of the choice property.
     * @return possible object is {@link Boolean }
     */
    public boolean isChoice()
    {
        if (choice == null)
        {
            return true;
        }
        else
        {
            return choice;
        }
    }

    /**
     * Sets the value of the choice property.
     * @param value allowed object is {@link Boolean }
     */
    public void setChoice(Boolean value)
    {
        this.choice = value;
    }

    /**
     * Gets the value of the choiceExit property.
     * @return possible object is {@link Boolean }
     */
    public boolean isChoiceExit()
    {
        if (choiceExit == null)
        {
            return true;
        }
        else
        {
            return choiceExit;
        }
    }

    /**
     * Sets the value of the choiceExit property.
     * @param value allowed object is {@link Boolean }
     */
    public void setChoiceExit(Boolean value)
    {
        this.choiceExit = value;
    }

    /**
     * Gets the value of the flow property.
     * @return possible object is {@link Boolean }
     */
    public boolean isFlow()
    {
        if (flow == null)
        {
            return false;
        }
        else
        {
            return flow;
        }
    }

    /**
     * Sets the value of the flow property.
     * @param value allowed object is {@link Boolean }
     */
    public void setFlow(Boolean value)
    {
        this.flow = value;
    }

    /**
     * Gets the value of the forwardOnly property.
     * @return possible object is {@link Boolean }
     */
    public boolean isForwardOnly()
    {
        if (forwardOnly == null)
        {
            return false;
        }
        else
        {
            return forwardOnly;
        }
    }

    /**
     * Sets the value of the forwardOnly property.
     * @param value allowed object is {@link Boolean }
     */
    public void setForwardOnly(Boolean value)
    {
        this.forwardOnly = value;
    }

    /**
     * Gets the value of the useCurrentAttemptObjectiveInfo property.
     * @return possible object is {@link Boolean }
     */
    public boolean isUseCurrentAttemptObjectiveInfo()
    {
        if (useCurrentAttemptObjectiveInfo == null)
        {
            return true;
        }
        else
        {
            return useCurrentAttemptObjectiveInfo;
        }
    }

    /**
     * Sets the value of the useCurrentAttemptObjectiveInfo property.
     * @param value allowed object is {@link Boolean }
     */
    public void setUseCurrentAttemptObjectiveInfo(Boolean value)
    {
        this.useCurrentAttemptObjectiveInfo = value;
    }

    /**
     * Gets the value of the useCurrentAttemptProgressInfo property.
     * @return possible object is {@link Boolean }
     */
    public boolean isUseCurrentAttemptProgressInfo()
    {
        if (useCurrentAttemptProgressInfo == null)
        {
            return true;
        }
        else
        {
            return useCurrentAttemptProgressInfo;
        }
    }

    /**
     * Sets the value of the useCurrentAttemptProgressInfo property.
     * @param value allowed object is {@link Boolean }
     */
    public void setUseCurrentAttemptProgressInfo(Boolean value)
    {
        this.useCurrentAttemptProgressInfo = value;
    }

}
