/**
 *
 * E-learning Module for Magnolia CMS (http://www.openmindlab.com/lab/products/lms.html)
 * Copyright(C) 2010-2011, Openmind S.r.l. http://www.openmindonline.it
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 12:53:38 PM CEST 
//

package net.sourceforge.openutils.mgnllms.scorm.model.imsss;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for objectiveBase complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="objectiveBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="minNormalizedMeasure" type="{http://www.imsglobal.org/xsd/imsss}measure" minOccurs="0"/>
 *         &lt;element name="mapInfo" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.imsglobal.org/xsd/imsss}objectiveMapping">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="satisfiedByMeasure" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "objectiveBase", propOrder = {"minNormalizedMeasure", "mapInfo" })
@XmlSeeAlso({PrimaryObjective.class, Objective.class })
public class ObjectiveBase
{

    @XmlElement(defaultValue = "1.00000")
    protected BigDecimal minNormalizedMeasure;

    protected List<MapInfo> mapInfo;

    @XmlAttribute
    protected Boolean satisfiedByMeasure;

    /**
     * Gets the value of the minNormalizedMeasure property.
     * @return possible object is {@link BigDecimal }
     */
    public BigDecimal getMinNormalizedMeasure()
    {
        return minNormalizedMeasure;
    }

    /**
     * Sets the value of the minNormalizedMeasure property.
     * @param value allowed object is {@link BigDecimal }
     */
    public void setMinNormalizedMeasure(BigDecimal value)
    {
        this.minNormalizedMeasure = value;
    }

    /**
     * Gets the value of the mapInfo property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the mapInfo property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     *    getMapInfo().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link MapInfo }
     */
    public List<MapInfo> getMapInfo()
    {
        if (mapInfo == null)
        {
            mapInfo = new ArrayList<MapInfo>();
        }
        return this.mapInfo;
    }

    /**
     * Gets the value of the satisfiedByMeasure property.
     * @return possible object is {@link Boolean }
     */
    public boolean isSatisfiedByMeasure()
    {
        if (satisfiedByMeasure == null)
        {
            return false;
        }
        else
        {
            return satisfiedByMeasure;
        }
    }

    /**
     * Sets the value of the satisfiedByMeasure property.
     * @param value allowed object is {@link Boolean }
     */
    public void setSatisfiedByMeasure(Boolean value)
    {
        this.satisfiedByMeasure = value;
    }

}
