/**
 *
 * E-learning Module for Magnolia CMS (http://www.openmindlab.com/lab/products/lms.html)
 * Copyright(C) 2010-2012, Openmind S.r.l. http://www.openmindonline.it
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 12:53:38 PM CEST 
//

package net.sourceforge.openutils.mgnllms.scorm.model.imsss;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * net.sourceforge.openutils.mgnllms.scorm.model.imsss package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 */
@XmlRegistry
public class ObjectFactory
{

    private final static QName _Sequencing_QNAME = new QName("http://www.imsglobal.org/xsd/imsss", "sequencing");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * net.sourceforge.openutils.mgnllms.scorm.model.imsss
     */
    public ObjectFactory()
    {
    }

    /**
     * Create an instance of {@link DeliveryControls }
     */
    public DeliveryControls createDeliveryControls()
    {
        return new DeliveryControls();
    }

    /**
     * Create an instance of {@link RuleCondition }
     */
    public RuleCondition createRuleCondition()
    {
        return new RuleCondition();
    }

    /**
     * Create an instance of {@link RuleActionPostCondition }
     */
    public RuleActionPostCondition createRuleActionPostCondition()
    {
        return new RuleActionPostCondition();
    }

    /**
     * Create an instance of {@link Objectives }
     */
    public Objectives createObjectives()
    {
        return new Objectives();
    }

    /**
     * Create an instance of {@link RuleActionPreCondition }
     */
    public RuleActionPreCondition createRuleActionPreCondition()
    {
        return new RuleActionPreCondition();
    }

    /**
     * Create an instance of {@link PreConditionRule }
     */
    public PreConditionRule createPreConditionRule()
    {
        return new PreConditionRule();
    }

    /**
     * Create an instance of {@link AuxiliaryResources }
     */
    public AuxiliaryResources createAuxiliaryResources()
    {
        return new AuxiliaryResources();
    }

    /**
     * Create an instance of {@link RuleConditions }
     */
    public RuleConditions createRuleConditions()
    {
        return new RuleConditions();
    }

    /**
     * Create an instance of {@link SequencingCollection }
     */
    public SequencingCollection createSequencingCollection()
    {
        return new SequencingCollection();
    }

    /**
     * Create an instance of {@link Randomization }
     */
    public Randomization createRandomization()
    {
        return new Randomization();
    }

    /**
     * Create an instance of {@link ObjectiveBase }
     */
    public ObjectiveBase createObjectiveBase()
    {
        return new ObjectiveBase();
    }

    /**
     * Create an instance of {@link RollupConditions }
     */
    public RollupConditions createRollupConditions()
    {
        return new RollupConditions();
    }

    /**
     * Create an instance of {@link SequencingRules }
     */
    public SequencingRules createSequencingRules()
    {
        return new SequencingRules();
    }

    /**
     * Create an instance of {@link RollupRules }
     */
    public RollupRules createRollupRules()
    {
        return new RollupRules();
    }

    /**
     * Create an instance of {@link RollupAction }
     */
    public RollupAction createRollupAction()
    {
        return new RollupAction();
    }

    /**
     * Create an instance of {@link LimitConditions }
     */
    public LimitConditions createLimitConditions()
    {
        return new LimitConditions();
    }

    /**
     * Create an instance of {@link RollupCondition }
     */
    public RollupCondition createRollupCondition()
    {
        return new RollupCondition();
    }

    /**
     * Create an instance of {@link AuxiliaryResource }
     */
    public AuxiliaryResource createAuxiliaryResource()
    {
        return new AuxiliaryResource();
    }

    /**
     * Create an instance of {@link Sequencing }
     */
    public Sequencing createSequencing()
    {
        return new Sequencing();
    }

    /**
     * Create an instance of {@link ExitConditionRule }
     */
    public ExitConditionRule createExitConditionRule()
    {
        return new ExitConditionRule();
    }

    /**
     * Create an instance of {@link ControlMode }
     */
    public ControlMode createControlMode()
    {
        return new ControlMode();
    }

    /**
     * Create an instance of {@link Objective }
     */
    public Objective createObjective()
    {
        return new Objective();
    }

    /**
     * Create an instance of {@link RuleActionExitCondition }
     */
    public RuleActionExitCondition createRuleActionExitCondition()
    {
        return new RuleActionExitCondition();
    }

    /**
     * Create an instance of {@link ObjectiveMapping }
     */
    public ObjectiveMapping createObjectiveMapping()
    {
        return new ObjectiveMapping();
    }

    /**
     * Create an instance of {@link PostConditionRule }
     */
    public PostConditionRule createPostConditionRule()
    {
        return new PostConditionRule();
    }

    /**
     * Create an instance of {@link MapInfo }
     */
    public MapInfo createMapInfo()
    {
        return new MapInfo();
    }

    /**
     * Create an instance of {@link PrimaryObjective }
     */
    public PrimaryObjective createPrimaryObjective()
    {
        return new PrimaryObjective();
    }

    /**
     * Create an instance of {@link RollupRule }
     */
    public RollupRule createRollupRule()
    {
        return new RollupRule();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sequencing }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsss", name = "sequencing")
    public JAXBElement<Sequencing> createSequencing(Sequencing value)
    {
        return new JAXBElement<Sequencing>(_Sequencing_QNAME, Sequencing.class, null, value);
    }

}
