/**
 *
 * E-learning Module for Magnolia CMS (http://www.openmindlab.com/lab/products/lms.html)
 * Copyright(C) 2010-2012, Openmind S.r.l. http://www.openmindonline.it
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 12:53:38 PM CEST 
//

package net.sourceforge.openutils.mgnllms.scorm.model.imsss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * The type that describes an individual objective mapping. Mapping one local objective GUID to one global objective
 * GUID
 * <p>
 * Java class for objectiveMapping complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="objectiveMapping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="targetObjectiveID" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="readSatisfiedStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="readNormalizedMeasure" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="writeSatisfiedStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="writeNormalizedMeasure" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "objectiveMapping")
@XmlSeeAlso({MapInfo.class })
public class ObjectiveMapping
{

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String targetObjectiveID;

    @XmlAttribute
    protected Boolean readSatisfiedStatus;

    @XmlAttribute
    protected Boolean readNormalizedMeasure;

    @XmlAttribute
    protected Boolean writeSatisfiedStatus;

    @XmlAttribute
    protected Boolean writeNormalizedMeasure;

    /**
     * Gets the value of the targetObjectiveID property.
     * @return possible object is {@link String }
     */
    public String getTargetObjectiveID()
    {
        return targetObjectiveID;
    }

    /**
     * Sets the value of the targetObjectiveID property.
     * @param value allowed object is {@link String }
     */
    public void setTargetObjectiveID(String value)
    {
        this.targetObjectiveID = value;
    }

    /**
     * Gets the value of the readSatisfiedStatus property.
     * @return possible object is {@link Boolean }
     */
    public boolean isReadSatisfiedStatus()
    {
        if (readSatisfiedStatus == null)
        {
            return true;
        }
        else
        {
            return readSatisfiedStatus;
        }
    }

    /**
     * Sets the value of the readSatisfiedStatus property.
     * @param value allowed object is {@link Boolean }
     */
    public void setReadSatisfiedStatus(Boolean value)
    {
        this.readSatisfiedStatus = value;
    }

    /**
     * Gets the value of the readNormalizedMeasure property.
     * @return possible object is {@link Boolean }
     */
    public boolean isReadNormalizedMeasure()
    {
        if (readNormalizedMeasure == null)
        {
            return true;
        }
        else
        {
            return readNormalizedMeasure;
        }
    }

    /**
     * Sets the value of the readNormalizedMeasure property.
     * @param value allowed object is {@link Boolean }
     */
    public void setReadNormalizedMeasure(Boolean value)
    {
        this.readNormalizedMeasure = value;
    }

    /**
     * Gets the value of the writeSatisfiedStatus property.
     * @return possible object is {@link Boolean }
     */
    public boolean isWriteSatisfiedStatus()
    {
        if (writeSatisfiedStatus == null)
        {
            return false;
        }
        else
        {
            return writeSatisfiedStatus;
        }
    }

    /**
     * Sets the value of the writeSatisfiedStatus property.
     * @param value allowed object is {@link Boolean }
     */
    public void setWriteSatisfiedStatus(Boolean value)
    {
        this.writeSatisfiedStatus = value;
    }

    /**
     * Gets the value of the writeNormalizedMeasure property.
     * @return possible object is {@link Boolean }
     */
    public boolean isWriteNormalizedMeasure()
    {
        if (writeNormalizedMeasure == null)
        {
            return false;
        }
        else
        {
            return writeNormalizedMeasure;
        }
    }

    /**
     * Sets the value of the writeNormalizedMeasure property.
     * @param value allowed object is {@link Boolean }
     */
    public void setWriteNormalizedMeasure(Boolean value)
    {
        this.writeNormalizedMeasure = value;
    }

}
