/**
 *
 * E-learning Module for Magnolia CMS (http://www.openmindlab.com/lab/products/lms.html)
 * Copyright(C) 2010-2013, Openmind S.r.l. http://www.openmindonline.it
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 12:53:38 PM CEST 
//

package net.sourceforge.openutils.mgnllms.scorm.model.imsss;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for randomization complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="randomization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="randomizationTiming" type="{http://www.imsglobal.org/xsd/imsss}randomTiming" default="never" />
 *       &lt;attribute name="selectCount" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="reorderChildren" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="selectionTiming" type="{http://www.imsglobal.org/xsd/imsss}randomTiming" default="never" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "randomization")
public class Randomization
{

    @XmlAttribute
    protected RandomTiming randomizationTiming;

    @XmlAttribute
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger selectCount;

    @XmlAttribute
    protected Boolean reorderChildren;

    @XmlAttribute
    protected RandomTiming selectionTiming;

    /**
     * Gets the value of the randomizationTiming property.
     * @return possible object is {@link RandomTiming }
     */
    public RandomTiming getRandomizationTiming()
    {
        if (randomizationTiming == null)
        {
            return RandomTiming.NEVER;
        }
        else
        {
            return randomizationTiming;
        }
    }

    /**
     * Sets the value of the randomizationTiming property.
     * @param value allowed object is {@link RandomTiming }
     */
    public void setRandomizationTiming(RandomTiming value)
    {
        this.randomizationTiming = value;
    }

    /**
     * Gets the value of the selectCount property.
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getSelectCount()
    {
        return selectCount;
    }

    /**
     * Sets the value of the selectCount property.
     * @param value allowed object is {@link BigInteger }
     */
    public void setSelectCount(BigInteger value)
    {
        this.selectCount = value;
    }

    /**
     * Gets the value of the reorderChildren property.
     * @return possible object is {@link Boolean }
     */
    public boolean isReorderChildren()
    {
        if (reorderChildren == null)
        {
            return false;
        }
        else
        {
            return reorderChildren;
        }
    }

    /**
     * Sets the value of the reorderChildren property.
     * @param value allowed object is {@link Boolean }
     */
    public void setReorderChildren(Boolean value)
    {
        this.reorderChildren = value;
    }

    /**
     * Gets the value of the selectionTiming property.
     * @return possible object is {@link RandomTiming }
     */
    public RandomTiming getSelectionTiming()
    {
        if (selectionTiming == null)
        {
            return RandomTiming.NEVER;
        }
        else
        {
            return selectionTiming;
        }
    }

    /**
     * Sets the value of the selectionTiming property.
     * @param value allowed object is {@link RandomTiming }
     */
    public void setSelectionTiming(RandomTiming value)
    {
        this.selectionTiming = value;
    }

}
