/**
 *
 * E-learning Module for Magnolia CMS (http://www.openmindlab.com/lab/products/lms.html)
 * Copyright(C) 2010-2012, Openmind S.r.l. http://www.openmindonline.it
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 12:53:38 PM CEST 
//

package net.sourceforge.openutils.mgnllms.scorm.model.imsss;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="referencedObjective" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="measureThreshold" type="{http://www.imsglobal.org/xsd/imsss}measure" />
 *       &lt;attribute name="operator" type="{http://www.imsglobal.org/xsd/imsss}conditionOperator" default="noOp" />
 *       &lt;attribute name="condition" use="required" type="{http://www.imsglobal.org/xsd/imsss}sequencingRuleCondition" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class RuleCondition
{

    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String referencedObjective;

    @XmlAttribute
    protected BigDecimal measureThreshold;

    @XmlAttribute
    protected ConditionOperator operator;

    @XmlAttribute(required = true)
    protected SequencingRuleCondition condition;

    /**
     * Gets the value of the referencedObjective property.
     * @return possible object is {@link String }
     */
    public String getReferencedObjective()
    {
        return referencedObjective;
    }

    /**
     * Sets the value of the referencedObjective property.
     * @param value allowed object is {@link String }
     */
    public void setReferencedObjective(String value)
    {
        this.referencedObjective = value;
    }

    /**
     * Gets the value of the measureThreshold property.
     * @return possible object is {@link BigDecimal }
     */
    public BigDecimal getMeasureThreshold()
    {
        return measureThreshold;
    }

    /**
     * Sets the value of the measureThreshold property.
     * @param value allowed object is {@link BigDecimal }
     */
    public void setMeasureThreshold(BigDecimal value)
    {
        this.measureThreshold = value;
    }

    /**
     * Gets the value of the operator property.
     * @return possible object is {@link ConditionOperator }
     */
    public ConditionOperator getOperator()
    {
        if (operator == null)
        {
            return ConditionOperator.NO_OP;
        }
        else
        {
            return operator;
        }
    }

    /**
     * Sets the value of the operator property.
     * @param value allowed object is {@link ConditionOperator }
     */
    public void setOperator(ConditionOperator value)
    {
        this.operator = value;
    }

    /**
     * Gets the value of the condition property.
     * @return possible object is {@link SequencingRuleCondition }
     */
    public SequencingRuleCondition getCondition()
    {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * @param value allowed object is {@link SequencingRuleCondition }
     */
    public void setCondition(SequencingRuleCondition value)
    {
        this.condition = value;
    }

}
