/**
 *
 * E-learning Module for Magnolia CMS (http://www.openmindlab.com/lab/products/lms.html)
 * Copyright(C) 2010-2011, Openmind S.r.l. http://www.openmindonline.it
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 12:53:38 PM CEST 
//

package net.sourceforge.openutils.mgnllms.scorm.model.nav;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for hideLMSUI.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="hideLMSUI">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="abandon"/>
 *     &lt;enumeration value="continue"/>
 *     &lt;enumeration value="exit"/>
 *     &lt;enumeration value="previous"/>
 *     &lt;enumeration value="suspendAll"/>
 *     &lt;enumeration value="exitAll"/>
 *     &lt;enumeration value="abandonAll"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "hideLMSUI")
@XmlEnum
public enum HideLMSUI {

    @XmlEnumValue("abandon")
    ABANDON("abandon"), @XmlEnumValue("continue")
    CONTINUE("continue"), @XmlEnumValue("exit")
    EXIT("exit"), @XmlEnumValue("previous")
    PREVIOUS("previous"), @XmlEnumValue("suspendAll")
    SUSPENDALL("suspendAll"), @XmlEnumValue("exitAll")
    EXITALL("exitAll"), @XmlEnumValue("abandonAll")
    ABANDONALL("abandonAll");

    private final String value;

    HideLMSUI(String v)
    {
        value = v;
    }

    public String value()
    {
        return value;
    }

    public static HideLMSUI fromValue(String v)
    {
        for (HideLMSUI c : HideLMSUI.values())
        {
            if (c.value.equals(v))
            {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
